export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export const REMOVE_POST_BY_ID = 'REMOVE_POST_BY_ID';
export const SET_ACTIVE_POST = 'SET_ACTIVE_POST';
