export const postsList = [
  {
    id: '111',
    author: { name: '111 author' },
    title: '111 title',
    created: 10800000,
    preview: { images: [{ resolutions: [{ url: 'https://image1111.com' }] }] },
    comments: [],
  },
  {
    id: '222',
    author: { name: '222 author' },
    title: '222 title',
    created: 10800000,
    preview: { images: [{ resolutions: [{ url: 'https://image222.com' }] }] },
    comments: [],
  },
  {
    id: '333',
    author: { name: '333 author' },
    title: '333 title',
    created: 10800000,
    preview: { images: [{ resolutions: [{ url: 'https://image333.com' }] }] },
    comments: [],
  },
  {
    id: '444',
    author: { name: '444 author' },
    title: '444 title',
    created: 10800000,
    preview: { images: [{ resolutions: [{ url: 'https://image444.com' }] }] },
    comments: [],
  },
  {
    id: '555',
    author: { name: '555 author' },
    title: '555 title',
    created: 10800000,
    preview: { images: [{ resolutions: [{ url: 'https://image555.com' }] }] },
    comments: [],
  },
];
